sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: happy_tassie_travel
    username: root
    password: abc123
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: hmlead22
    access-key-id: LTAI5tGP1rQXTQvbNSNRU5un
    access-key-secret: 6HF0pIVdu9ADn1lCRWIjlFjsgX2qxI
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx6a4d9f9390fa4e49
    secret: fd706c40e9a471ff19bd9cf947321398

# OpenWeatherMap 天气API配置
weather:
  openweathermap:
    api-key: ec19e77fd31ded1dd1880d1f64f49c91
    base-url: http://api.openweathermap.org/data/2.5
    enabled: true
    cache-duration: 600

# 生产环境日志配置
logging:
  level:
    com:
      sky:
        mapper: info
        service: info
        controller: info
    root: info
  file:
    name: /opt/sky-takeout/logs/sky-takeout.log
    max-size: 100MB
    max-history: 30
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 