sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: happy_tassie_travel
    username: root
    password: ${DATABASE_PASSWORD:your-database-password}
  alioss:
    endpoint: oss-cn-hongkong.aliyuncs.com
    bucket-name: happy-tassie-hongkong
    access-key-id: ${ALIYUN_OSS_ACCESS_KEY_ID:your-access-key-id}
    access-key-secret: ${ALIYUN_OSS_ACCESS_KEY_SECRET:your-access-key-secret}
  redis:
    host: localhost
    port: 6379
    database: 7
  wechat:
    appid: wx6a4d9f9390fa4e49
    secret: ${WECHAT_APP_SECRET:your-wechat-app-secret}
  mail:
    enabled: true  # 启用邮件发送功能
    host: smtp.gmail.com
    port: 587
    username: Tom.zhang@htas.com.au  # 需要配置真实邮箱
    password: ${EMAIL_PASSWORD:your-email-password}  # 需要配置真实密码
    from: Tom.zhang@htas.com.au
  email:
    encryption-key: ${EMAIL_ENCRYPTION_KEY:your-32-character-encryption-key}  # 员工邮箱密码加密密钥（32字节）

# Spring Mail配置
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: Tom.zhang@htas.com.au
    password: ${EMAIL_PASSWORD:your-email-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 25000

# OpenWeatherMap 天气API配置
weather:
  openweathermap:
    api-key: ${WEATHER_API_KEY:your-openweather-api-key}  # Active状态的API Key
    base-url: http://api.openweathermap.org/data/2.5
    enabled: true  # 启用天气功能
    cache-duration: 600  # 缓存10分钟（API建议不超过10分钟请求一次）
