sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:3306}
    database: ${DB_NAME:happy_tassie_travel}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:abc123}
  alioss:
    endpoint: ${ALIYUN_OSS_ENDPOINT:oss-cn-hongkong.aliyuncs.com}
    bucket-name: ${ALIYUN_OSS_BUCKET:happytassieholiday}
    access-key-id: ${ALIYUN_OSS_ACCESS_KEY_ID:your-access-key-id}
    access-key-secret: ${ALIYUN_OSS_ACCESS_KEY_SECRET:your-access-key-secret}
    cdn-domain: https://happytassieholiday.oss-cn-hongkong.aliyuncs.com
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:0}
  wechat:
    appid: ${WECHAT_APPID:your-wechat-appid}
    secret: ${WECHAT_SECRET:your-wechat-secret}
  mail:
    enabled: true  # 启用邮件发送
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:your-email@gmail.com}
    password: ${GMAIL_PASSWORD:your-gmail-app-password}
    from: ${GMAIL_USERNAME:your-email@gmail.com}

# Google OAuth 配置
google:
  oauth:
    client-id: ${GOOGLE_OAUTH_CLIENT_ID:your-google-client-id}
    client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET:your-google-client-secret}
    redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:3001/auth/google/callback}
    scope: openid email profile
  email:
    encryption-key: ${EMAIL_ENCRYPTION_KEY:your-32-char-encryption-key}

# OpenWeatherMap 天气API配置
weather:
  openweathermap:
    api-key: ${WEATHER_API_KEY:your-weather-api-key}
    base-url: http://api.openweathermap.org/data/2.5
    enabled: true
    cache-duration: 600

# 生产环境日志配置
logging:
  level:
    com:
      sky:
        mapper: info
        service: info
        controller: info
    root: info
  file:
    name: /opt/sky-takeout/logs/sky-takeout.log
    max-size: 100MB
    max-history: 30
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 