sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: happy_tassie_travel
    username: root  
    password: abc123  # 与部署脚本保持一致
  alioss:
    endpoint: oss-cn-hongkong.aliyuncs.com
    bucket-name: happy-tassie-hongkong
    access-key-id: ${ALIYUN_OSS_ACCESS_KEY_ID:your-access-key-id}
    access-key-secret: ${ALIYUN_OSS_ACCESS_KEY_SECRET:your-access-key-secret}
    cdn-domain: https://happy-tassie-hongkong.oss-cn-hongkong.aliyuncs.com
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx6a4d9f9390fa4e49
    secret: ${WECHAT_SECRET:your-wechat-secret}
  mail:
    enabled: true  # 启用邮件发送
    host: smtp.gmail.com
    port: 587
    username: "Tom.zhang@htas.com.au"
    password: ${MAIL_PASSWORD:your-mail-password}
    from: "Tom.zhang@htas.com.au"

# OpenWeatherMap 天气API配置
weather:
  openweathermap:
    api-key: ${WEATHER_API_KEY:your-weather-api-key}
    base-url: http://api.openweathermap.org/data/2.5
    enabled: true
    cache-duration: 600

# 生产环境日志配置
logging:
  level:
    com:
      sky:
        mapper: info
        service: info
        controller: info
    root: info
  file:
    name: /opt/sky-takeout/logs/sky-takeout.log
    max-size: 100MB
    max-history: 30
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 