sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: happy_tassie_travel
    username: root
    password: abc123
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: your-bucket-name
    access-key-id: YOUR_ACCESS_KEY_ID
    access-key-secret: YOUR_ACCESS_KEY_SECRET
  redis:
    host: localhost
    port: 6379
    database: 7
  wechat:
    appid: YOUR_WECHAT_APPID
    secret: YOUR_WECHAT_SECRET

# OpenWeatherMap 天气API配置
weather:
  openweathermap:
    api-key: YOUR_OPENWEATHER_API_KEY
    base-url: http://api.openweathermap.org/data/2.5
    enabled: true
    cache-duration: 600
