version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: happy-tassie-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  # Redis缓存
  redis:
    image: redis:6-alpine
    container_name: happy-tassie-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Spring Boot应用
  app:
    build: .
    container_name: happy-tassie-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=mysql
      - REDIS_HOST=redis
    env_file:
      - .env

volumes:
  mysql_data:
  redis_data:
